config/routes.rb
TableAccessRight::Application.routes.draw do
  get "sys_module_mappings/index"

  get "sys_module_mappings/new"

  get "sys_module_mappings/create"

  get "sys_module_mappings/edit"

  get "sys_module_mappings/update"

  get "sys_module_mappings/destroy"

  get "sys_user_groups/index"

  get "sys_user_groups/new"

  get "sys_user_groups/create"

  get "sys_user_groups/edit"

  get "sys_user_groups/update"

  get "sys_user_groups/destroy"

  get "sys_user_position_groups/index"

  get "sys_user_position_groups/new"

  get "sys_user_position_groups/create"

  get "sys_user_position_groups/edit"

  get "sys_user_position_groups/update"

  get "sys_user_position_groups/destroy"

  get "sys_position_and_groups/index"

  get "sys_position_and_groups/new"

  get "sys_position_and_groups/create"

  get "sys_position_and_groups/edit"

  get "sys_position_and_groups/update"

  get "sys_position_and_groups/destroy"

  get "sys_modules/index"

  get "sys_modules/new"

  get "sys_modules/create"

  get "sys_modules/edit"

  get "sys_modules/update"

  get "sys_modules/destroy"

  get "sys_user_rights/index"

  get "sys_user_rights/new"

  get "sys_user_rights/create"

  get "sys_user_rights/destroy"

  get "sys_action_on_tables/index"

  get "sys_action_on_tables/new"

  get "sys_action_on_tables/create"

  get "sys_action_on_tables/edit"

  get "sys_action_on_tables/update"

  get "sys_action_on_tables/destroy"

  get "main_menus/index"

  get "sys_user_positions/index"

  get "sys_user_positions/new"

  get "sys_user_positions/create"

  get "sys_user_positions/edit"

  get "sys_user_positions/update"
  
  
  resources :sys_user_groups
  resources :sys_action_on_tables
  resources :sys_modules
  resources :sys_module_mappings
  resources :sys_user_rights do
    collection do
      get 'search' 
      put 'search_results'
    end
  end

    root :to => "main_menus#index"
end

app/models/sys_user_right.rb
# encoding: utf-8
class SysUserRight < ActiveRecord::Base
  attr_accessible :sys_action_on_table_id, :sys_user_group_id, :matching_column_name, :as => :role_new_update
  attr_accessor :sys_action_on_table_s, :sys_user_position_s, :table_name_s
  attr_accessible :sys_action_on_table_s, :sys_user_position_s, :table_name_s, :as => :role_search
  
  belongs_to :sys_action_on_table
  belongs_to :sys_user_group
  
  validates_presence_of :sys_action_on_table_id
  validates_presence_of :sys_user_group_id
  validates :sys_action_on_table_id, :uniqueness => {:scope => :sys_user_group_id}
  
  def find_sys_user_rights
    rights = SysUserRight.order("sys_user_group_id, sys_action_on_table_id")
    rights = rights.where("sys_user_group_id = ?", sys_user_position_s) if sys_user_position_s.present?
    rights = rights.joins(:sys_action_on_table).where("sys_action_on_tables.action = ?", sys_action_on_table_s) if sys_action_on_table_s.present?
    rights = rights.joins(:sys_action_on_table).where("sys_action_on_tables.table_name = ?", table_name_s) if table_name_s.present?
    rights
  end
end

app/controllers/sys_user_rights_controller.rb
# encoding: utf-8
class SysUserRightsController < ApplicationController
  def index
    @sys_user_rights = SysUserRight.order("sys_user_group_id, sys_action_on_table_id")
  end

  def new
    @sys_user_right = SysUserRight.new
  end

  def create
    @sys_user_right = SysUserRight.new(params[:sys_user_right], :as => :role_new_update)
    if @sys_user_right.save
      redirect_to sys_user_rights_path, :notice => 'Saved!'
    else
      flash[:notice] = 'Data error. NOT saved'
      render 'new'
    end
  end

  def destroy
    @sys_user_right = SysUserRight.find(params[:id])
    if @sys_user_right.destroy
      flash[:notice] = 'Deleted!'
    else
      flash[:notice] = 'NOT deleted!'
    end
  end
  
  def search
    @sys_user_right = SysUserRight.new(params[:sys_user_right], :as => :role_search)
  end
  
  def search_results
    @sys_user_right = SysUserRight.new(params[:sys_user_right], :as => :role_search)
    @sys_user_rights = @sys_user_right.find_sys_user_rights
    #seach params
    @search_params = search_params()    
  end
  
  protected
  
  def search_params
    search_params = "参数："
    search_params += ' TableName：' + params[:sys_user_right][:table_name_s] if params[:sys_user_right][:table_name_s].present?
    search_params += ', 用户群：' + SysUserGroup.find(params[:sys_user_right][:sys_user_position_s].to_i).position if params[:sys_user_right][:sys_user_position_s].present?
    search_params += ', 操作 ：' + params[:sys_user_right][:sys_action_on_table_s] if params[:sys_user_right][:sys_action_on_table_s].present?
    search_params
  end  
  
end

app/helpers/sys_user_rights_helper.rb
module SysUserRightsHelper
end

app/views/sys_user_rights/_form.html.erb
<%= simple_form_for(@sys_user_right) do |f| %>

  <%= f.input :sys_action_on_table_id, :label => '数据表/操作：', :collection => SysActionOnTable.order("table_name, action"), :label_method => lambda { |r| "#{r.action}, - #{r.table_name}"},
                           :value_method => :id, :include_blank => true %>
  <%= f.input :sys_user_group_id, :label => '用户群/PositionGroup:', :collection => SysUserGroup.order("user_group_name"), :label_method => lambda {|r| "#{r.user_group_name}, - #{r.short_note}"}, 
                           :value_method => :id,  :include_blank => true %>                           
  <%= f.input :matching_column_name, :lable => 'MatchingColumnName:' %>
  <%= f.button :submit, '保存' %>  

<% end %>

app/views/sys_user_rights/create.html.erb
<h1>SysUserRights#create</h1>
<p>Find me in app/views/sys_user_rights/create.html.erb</p>

app/views/sys_user_rights/destroy.html.erb
<h1>SysUserRights#destroy</h1>
<p>Find me in app/views/sys_user_rights/destroy.html.erb</p>

app/views/sys_user_rights/index.html.erb
<div id="main_body">
<h1>User Rights</h1>
<table>
  <tr>
  	<th>UserGroupName</th>
    <th>简注</th>
    <th>Action</th>
    <th>TableName</th>
    <th>MatchingColName</th>
    <th></th>  
  </tr>

<% @sys_user_rights.each do |p| %>
  <tr>
  	
    <td><%= p.sys_user_group.user_group_name if p.sys_user_group_id.present? %></td> 	
    <td><%= p.sys_user_group.short_note if p.sys_user_group_id.present? %></td> 
    <td><%= p.sys_action_on_table.action %></td>
    <td><%= p.sys_action_on_table.table_name %></td>
    <td><%= p.matching_column_name %></td>
    <td><%= link_to 'Delete', sys_user_right_path(p), :method => :delete, :confirm => 'Are you sure to delete?' %></td>
  </tr>
<% end %>

</table>
 
  <%= link_to "输入Right", new_sys_user_right_path(:format => :js), :remote => true, :id => 'new_log_link' %>
  <%= link_to 'Search', search_sys_user_rights_path, :id => 'search_link'%>

</div>

app/views/sys_user_rights/new.html.erb
<div id="main_body">
<h1>新Right</h1>

<%= render 'form' %>
<%= link_to 'Close', sys_user_rights_path %>
</div>

app/views/sys_user_rights/new.js.erb
$("<%= escape_javascript render(:file => 'sys_user_rights/new.html.erb') %>").insertAfter('#new_log_link');
$('#new_log_link').hide();
$('#search_link').hide();

app/views/sys_user_rights/search.html.erb
<div id="main_body">
<h1>Rights搜索</h1>
<%= simple_form_for @sys_user_right, :method => :put, :url => { :action => 'search_results' } do |f| %>    
  <%= f.input :table_name_s, :collection => ActiveRecord::Base.connection.tables, :prompt => "选Table Name", :label => "数据表名："  %>
  <%= f.input :sys_user_position_s, :label => "职位 /Position：", :collection => SysUserPositionGroup.order("position_group_name"), :label_method => lambda {|r| "#{r.position_group_name} - #{r.short_note}"}, :value_method => :id, :include_blank => true %> 
  <%= f.input :sys_action_on_table_s, :label => "操作/Action ：", :collection => SysActionOnTable.select("action").uniq, :label_method => :action, :value_method => :action, :include_blank => true %> 
  <%= f.button :submit, '搜索' %>  
<% end %> 
</div>

app/views/sys_user_rights/search_results.html.erb
<div id="main_body">
<h1>User Rigths搜索</h1>
<%=@search_params%>
<p>总数： <%=@sys_user_rights.count %>, 
	职位数量： <%= @sys_user_rights.select("DISTINCT(sys_user_position_id)").count %>,</p>
         数据表数目： <%= @sys_user_rights.joins(:sys_action_on_table).select("DISTINCT(table_name)").count %>, 
	操作数目： <%= @sys_user_rights.joins(:sys_action_on_table).select("DISTINCT(action)").count  %>,	
</p>		 

<table>
  <tr>
  	<th>PositionGroupName</th>
    <th>说明</th>
    <th>Action</th>
    <th>TableName</th>
    <th>MatchingColumnName</th>
    <th></th>  
  </tr>

<% @sys_user_rights.each do |p| %>
  <tr>
  	
    <td><%= p.sys_user_position_group.position_group_name %></td> 	
    <td><%= p.sys_user_position_group.short_note %></td> 
    <td><%= p.sys_action_on_table.action %></td>
    <td><%= p.sys_action_on_table.table_name %></td>
    <td><%= p.matching_column_name %></td>
    <td><%= link_to 'Delete', sys_user_right_path(p), :method => :delete, :confirm => 'Are you sure to delete?' %></td>
  </tr>
<% end %>

</table>
 
  <%= link_to "输入Right", new_sys_user_right_path(:format => :js), :remote => true, :id => 'new_log_link' %>
  
</div>