config/routes.rb
TableAccessRight::Application.routes.draw do
  get "sys_module_mappings/index"

  get "sys_module_mappings/new"

  get "sys_module_mappings/create"

  get "sys_module_mappings/edit"

  get "sys_module_mappings/update"

  get "sys_module_mappings/destroy"

  get "sys_user_groups/index"

  get "sys_user_groups/new"

  get "sys_user_groups/create"

  get "sys_user_groups/edit"

  get "sys_user_groups/update"

  get "sys_user_groups/destroy"

  get "sys_user_position_groups/index"

  get "sys_user_position_groups/new"

  get "sys_user_position_groups/create"

  get "sys_user_position_groups/edit"

  get "sys_user_position_groups/update"

  get "sys_user_position_groups/destroy"

  get "sys_position_and_groups/index"

  get "sys_position_and_groups/new"

  get "sys_position_and_groups/create"

  get "sys_position_and_groups/edit"

  get "sys_position_and_groups/update"

  get "sys_position_and_groups/destroy"

  get "sys_modules/index"

  get "sys_modules/new"

  get "sys_modules/create"

  get "sys_modules/edit"

  get "sys_modules/update"

  get "sys_modules/destroy"

  get "sys_user_rights/index"

  get "sys_user_rights/new"

  get "sys_user_rights/create"

  get "sys_user_rights/destroy"

  get "sys_action_on_tables/index"

  get "sys_action_on_tables/new"

  get "sys_action_on_tables/create"

  get "sys_action_on_tables/edit"

  get "sys_action_on_tables/update"

  get "sys_action_on_tables/destroy"

  get "main_menus/index"

  get "sys_user_positions/index"

  get "sys_user_positions/new"

  get "sys_user_positions/create"

  get "sys_user_positions/edit"

  get "sys_user_positions/update"
  
  
  resources :sys_user_groups
  resources :sys_action_on_tables
  resources :sys_modules
  resources :sys_module_mappings
  resources :sys_user_rights do
    collection do
      get 'search' 
      put 'search_results'
    end
  end

    root :to => "main_menus#index"
end

app/controllers/main_menus_controller.rb
class MainMenusController < ApplicationController
  def index
    render 'main_menus/index'
  end
end

app/helpers/main_menus_helper.rb
module MainMenusHelper
end

app/views/main_menus/index.html.erb
<div id="user">
	<table width="90%">
		<tr>
			<td width="40%" valign="top">
				<ul>
					<li><%= link_to 'UserGroup/用户职位群', sys_user_groups_path %></li>	
					<li><%= link_to 'Modules', sys_modules_path %></li>
					<li><%= link_to 'Rights/用户权限', sys_user_rights_path %></li>					
 
				</ul>
				</td>
				<td width="20">&nbsp;</td>
				<td valign="top">
				<ul>
					<li><%= link_to 'Actions/数据表操作', sys_action_on_tables_path %></li>
					<li><%= link_to 'Position&Group', sys_module_mappings_path %></li>
				</ul>
			</td>
		</tr>
	</table>	
</div>