config/routes.rb
TableAccessRight::Application.routes.draw do
  get "sys_module_mappings/index"

  get "sys_module_mappings/new"

  get "sys_module_mappings/create"

  get "sys_module_mappings/edit"

  get "sys_module_mappings/update"

  get "sys_module_mappings/destroy"

  get "sys_user_groups/index"

  get "sys_user_groups/new"

  get "sys_user_groups/create"

  get "sys_user_groups/edit"

  get "sys_user_groups/update"

  get "sys_user_groups/destroy"

  get "sys_user_position_groups/index"

  get "sys_user_position_groups/new"

  get "sys_user_position_groups/create"

  get "sys_user_position_groups/edit"

  get "sys_user_position_groups/update"

  get "sys_user_position_groups/destroy"

  get "sys_position_and_groups/index"

  get "sys_position_and_groups/new"

  get "sys_position_and_groups/create"

  get "sys_position_and_groups/edit"

  get "sys_position_and_groups/update"

  get "sys_position_and_groups/destroy"

  get "sys_modules/index"

  get "sys_modules/new"

  get "sys_modules/create"

  get "sys_modules/edit"

  get "sys_modules/update"

  get "sys_modules/destroy"

  get "sys_user_rights/index"

  get "sys_user_rights/new"

  get "sys_user_rights/create"

  get "sys_user_rights/destroy"

  get "sys_action_on_tables/index"

  get "sys_action_on_tables/new"

  get "sys_action_on_tables/create"

  get "sys_action_on_tables/edit"

  get "sys_action_on_tables/update"

  get "sys_action_on_tables/destroy"

  get "main_menus/index"

  get "sys_user_positions/index"

  get "sys_user_positions/new"

  get "sys_user_positions/create"

  get "sys_user_positions/edit"

  get "sys_user_positions/update"
  
  
  resources :sys_user_groups
  resources :sys_action_on_tables
  resources :sys_modules
  resources :sys_module_mappings
  resources :sys_user_rights do
    collection do
      get 'search' 
      put 'search_results'
    end
  end

    root :to => "main_menus#index"
end

app/models/sys_module_mapping.rb
class SysModuleMapping < ActiveRecord::Base
  belongs_to :sys_user_group
  belongs_to :sys_module
  
  attr_accessible :sys_module_id, :sys_user_group_id, :as => :role_new
  
  validates_presence_of :sys_module_id
  validates_presence_of :sys_user_group_id
end

app/controllers/sys_module_mappings_controller.rb
# encoding: utf-8
class SysModuleMappingsController < ApplicationController
  def index
    @sys_module_mappings = SysModuleMapping.order("sys_module_id, sys_user_group_id")
  end

  def new
    @sys_module_mapping = SysModuleMapping.new
  end

  def create
    @sys_module_mapping = SysModuleMapping.new(params[:sys_module_mapping], :as => :role_new)
    if @sys_module_mapping.save
      redirect_to sys_module_mappings_path
    else
      flash.now[:notice] = 'Data error. Not saved!'
      render 'new'
    end
  end

  def edit
    @sys_module_mapping = SysModuleMapping.find(params[:id])
  end

  def update
    @sys_module_mapping = SysModuleMapping.find(params[:id])
    if @sys_module_mapping.update_attributes(params[:sys_module_mapping], :as => :role_new)
      redirect_to sys_module_mappings_path
    else
      flash.now[:notice] = 'Data error. Not modified!'
      render "edit"
    end
  end

  def destroy
    @sys_module_mapping = SysModuleMapping.find(params[:id])
    @sys_module_mapping.destroy
    redirect_to sys_module_mappings_path
  end
end

app/helpers/sys_module_mappings_helper.rb
module SysModuleMappingsHelper
end

app/views/sys_module_mappings/_form.html.erb
<%= simple_form_for(@sys_module_mapping) do |f| %>

  <%= f.input :sys_module_id, :label => 'Module/UserGroup:', :collection => SysModule.order("module_name, module_group_name"), :value_method => :id,
            :label_method => lambda {|r| "##{r.id}, #{r.module_name}, #{r.module_group}"}, :selected => @sys_module_mapping.sys_module_id, :include_blank => true %>
  <%= f.input :sys_user_group_id, :label => 'UserGroup:', :collection => SysUserGroup.order("user_group_name"), :value_method => :id,
            :label_method => :user_group_name, :selected => @sys_module_mapping.sys_user_group_id, :include_blank => true %>

  <%= f.button :submit, '保存' %>  
<% end %>

app/views/sys_module_mappings/create.html.erb
<h1>SysModuleMappings#create</h1>
<p>Find me in app/views/sys_module_mappings/create.html.erb</p>

app/views/sys_module_mappings/destroy.html.erb
<h1>SysModuleMappings#destroy</h1>
<p>Find me in app/views/sys_module_mappings/destroy.html.erb</p>

app/views/sys_module_mappings/edit.html.erb
<div id="main_body">
<h1>Modify Position Group</h1>

<%= render 'form' %>
<%= link_to 'Close', sys_module_mappings_path %>
</div>

app/views/sys_module_mappings/edit.js.erb
$("<%= escape_javascript render(:file => 'sys_module_mappings/edit.html.erb') %>").insertAfter('#new_log_link');
$('#new_log_link').hide();

app/views/sys_module_mappings/index.html.erb
<div id="main_body">
<h1>Position & Group</h1>
<table>
  <tr>
  	<th>#</th>
  	<th>UserGroup</th>
    <th>ModuleName</th>
    <th>ModuleMapping</th>
    <th></th> 
    <th></th> 
  </tr>

<% @sys_module_mappings.each do |p| %>
  <tr>
  	
    <td><%= p.id %></td> 
    <td><%= p.sys_user_group.user_group_name %></td> 	
    <td><%= p.sys_module.module_name %></td> 
    <td><%= p.sys_module.module_group_name %></td>
    <td><%= link_to 'Edit', edit_sys_module_mapping_path(p, :format => :js), :remote => true %></td>
    <td><%= link_to 'Delete', sys_module_mapping_path(p), :method => :delete, :confirm => 'Are you sure to delete?' %></td>
  </tr>
<% end %>

</table>

  <%= link_to "输入ModuleMapping", new_sys_module_mapping_path(:format => :js), :remote => true, :id => 'new_log_link' %>

</div>

app/views/sys_module_mappings/new.html.erb
<div id="main_body">
<h1>新ModuleMapping</h1>

<%= render 'form' %>
<%= link_to 'Close', sys_module_mappings_path %>
</div>

app/views/sys_module_mappings/new.js.erb
$("<%= escape_javascript render(:file => 'sys_module_mappings/new.html.erb') %>").insertAfter('#new_log_link');
$('#new_log_link').hide();

app/views/sys_module_mappings/update.html.erb
<h1>SysModuleMappings#update</h1>
<p>Find me in app/views/sys_module_mappings/update.html.erb</p>