config/routes.rb
TableAccessRight::Application.routes.draw do
  get "sys_module_mappings/index"

  get "sys_module_mappings/new"

  get "sys_module_mappings/create"

  get "sys_module_mappings/edit"

  get "sys_module_mappings/update"

  get "sys_module_mappings/destroy"

  get "sys_user_groups/index"

  get "sys_user_groups/new"

  get "sys_user_groups/create"

  get "sys_user_groups/edit"

  get "sys_user_groups/update"

  get "sys_user_groups/destroy"

  get "sys_user_position_groups/index"

  get "sys_user_position_groups/new"

  get "sys_user_position_groups/create"

  get "sys_user_position_groups/edit"

  get "sys_user_position_groups/update"

  get "sys_user_position_groups/destroy"

  get "sys_position_and_groups/index"

  get "sys_position_and_groups/new"

  get "sys_position_and_groups/create"

  get "sys_position_and_groups/edit"

  get "sys_position_and_groups/update"

  get "sys_position_and_groups/destroy"

  get "sys_modules/index"

  get "sys_modules/new"

  get "sys_modules/create"

  get "sys_modules/edit"

  get "sys_modules/update"

  get "sys_modules/destroy"

  get "sys_user_rights/index"

  get "sys_user_rights/new"

  get "sys_user_rights/create"

  get "sys_user_rights/destroy"

  get "sys_action_on_tables/index"

  get "sys_action_on_tables/new"

  get "sys_action_on_tables/create"

  get "sys_action_on_tables/edit"

  get "sys_action_on_tables/update"

  get "sys_action_on_tables/destroy"

  get "main_menus/index"

  get "sys_user_positions/index"

  get "sys_user_positions/new"

  get "sys_user_positions/create"

  get "sys_user_positions/edit"

  get "sys_user_positions/update"
  
  
  resources :sys_user_groups
  resources :sys_action_on_tables
  resources :sys_modules
  resources :sys_module_mappings
  resources :sys_user_rights do
    collection do
      get 'search' 
      put 'search_results'
    end
  end

    root :to => "main_menus#index"
end

app/models/sys_module.rb
class SysModule < ActiveRecord::Base
  attr_accessible :module_name, :module_group_name, :as => :role_new
  
  validates_presence_of :module_name
  validates_presence_of :module_group_name
end

app/controllers/sys_modules_controller.rb
# encoding: utf-8
class SysModulesController < ApplicationController
  def index
    @sys_modules = SysModule.order("module_name")
  end

  def new
    @sys_module = SysModule.new
  end

  def create
    @sys_module = SysModule.new(params[:sys_module], :as => :role_new)
    if @sys_module.save
      redirect_to sys_modules_path, :notice => 'Saved!'
    else
      flash.now[:notice] = 'Data error. Not saved!'
      render 'new'
    end
  end

  def edit
    @sys_module = SysModule.find(params[:id])
  end

  def update
    @sys_module = SysModule.find(params[:id])
    if @sys_module.update_attributes(params[:sys_module], :as => :role_new)
      redirect_to sys_modules_path, :notice => 'Modified!'
    else
      flash.now[:notice] = 'Data error. Not Modified!'
      render 'edit'
    end
  end

  def destroy
    @sys_module = SysModule.find(params[:id])
    @sys_module.transaction do
      SysModuleMapping.where("sys_module_id = ?", @sys_module.id).each do |r|
        r.destroy
      end
      @sys_module.destroy
    end
    redirect_to sys_modules_path, :notice => 'Destroyed'
  end
end

app/helpers/sys_modules_helper.rb
module SysModulesHelper
end

app/views/sys_modules/_form.html.erb
<%= simple_form_for(@sys_module) do |f| %>

  <%= f.input :module_name, :label => '模块名称/Module Name:' %>
  <%= f.input :module_group_name, :label => 'Module Group:' %>

  <%= f.button :submit, '保存' %>  
<% end %>

app/views/sys_modules/create.html.erb
<h1>SysModules#create</h1>
<p>Find me in app/views/sys_modules/create.html.erb</p>

app/views/sys_modules/destroy.html.erb
<h1>SysModules#destroy</h1>
<p>Find me in app/views/sys_modules/destroy.html.erb</p>

app/views/sys_modules/edit.html.erb
<div id="main_body">
<h1>Edit Module</h1>

<%= render 'form' %>
<%= link_to 'Close', sys_modules_path %>
</div>

app/views/sys_modules/edit.js.erb
$("<%= escape_javascript render(:file => 'sys_modules/edit.html.erb') %>").insertAfter('#new_log_link');
$('#new_log_link').hide();

app/views/sys_modules/index.html.erb
<div id="main_body">
<h1>Module</h1>
<table>
  <tr>
  	<th>#</th>
    <th>ModuleName</th>
    <th>ModuleGroup</th>
    <th></th> 
    <th></th> 
  </tr>

<% @sys_modules.each do |p| %>
  <tr>
  	
    <td><%= p.id %></td> 	
    <td><%= p.module_name %></td> 
    <td><%= p.module_group_name %></td>
    <td><%= link_to 'Edit', edit_sys_module_path(p, :format => :js), :remote => true %></td>
    <td><%= link_to 'Delete', sys_module_path(p), :method => :delete, :confirm => 'Are you sure to delete?' %></td>
  </tr>
<% end %>

</table>

  <%= link_to "输入Module&Group", new_sys_module_path(:format => :js), :remote => true, :id => 'new_log_link' %>

</div>

app/views/sys_modules/new.html.erb
<div id="main_body">
<h1>新Module</h1>

<%= render 'form' %>
<%= link_to 'Close', sys_modules_path %>
</div>

app/views/sys_modules/new.js.erb
$("<%= escape_javascript render(:file => 'sys_modules/new.html.erb') %>").insertAfter('#new_log_link');
$('#new_log_link').hide();

app/views/sys_modules/update.html.erb
<h1>SysModules#update</h1>
<p>Find me in app/views/sys_modules/update.html.erb</p>